config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usersApp.urls', namespace='usersApp'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

usersApp/urls.py
from django.urls import path

from usersApp.apps import UsersappConfig
from usersApp.views.user import Registration, LoginView, LogoutView, main, Profile, UserUpdateView, UserDeleteView

app_name = UsersappConfig.name

urlpatterns = [
    # main url
    path('', main, name='main'),
    # all users url
    path('user/registration', Registration.as_view(), name='registration'),
    path('user/login', LoginView.as_view(), name='login'),
    path('user/logout', LogoutView.as_view(), name='logout'),
    path('user/profile', Profile.as_view(), name='profile'),
    path('user/update', UserUpdateView.as_view(), name='update'),
    path('user/delete', UserDeleteView.as_view(), name='delete'),


]

usersApp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {
    'null': True,
    'blank': True,
}


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Почта')
    avatar = models.ImageField(upload_to='users/', **NULLABLE, verbose_name='Аватар')
    is_confirm = models.BooleanField(default=False, verbose_name='Подтверждение')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

usersApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import CheckboxInput

from usersApp.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if hasattr(field.widget, 'attrs') and not isinstance(field.widget, CheckboxInput):
                field.widget.attrs['class'] = 'form-control'


class UserForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']


class UserUpdate(StyleFormMixin, UserChangeForm):
    password = forms.CharField(widget=forms.HiddenInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'avatar', 'email', 'password']

usersApp/views.py
from django.shortcuts import render

# Create your views here.

usersApp/views/user.py
from django.contrib.auth.views import LoginView as BaseLoginView, LogoutView as BaseLogout
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import DetailView

from usersApp.forms import UserForm, UserUpdate
from usersApp.models import User


def main(request):
    return render(request, 'usersApp/main.html')


class LoginView(BaseLoginView):
    template_name = 'usersApp/login.html'


class LogoutView(BaseLogout):
    pass


class Registration(generic.CreateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('usersApp:login')
    template_name = 'usersApp/registration.html'


class Profile(DetailView):
    model = User

    def get_object(self, queryset=None):
        return self.request.user


class UserUpdateView(generic.UpdateView):
    model = User
    form_class = UserUpdate

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('usersApp:profile')


class UserDeleteView(generic.DeleteView):
    model = User

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('usersApp:login')

usersApp/templates/usersApp/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


</head>

<body style="padding-top: 70;">

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Главная</a>
        <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a class="nav-link " href="#">Статьи</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="#">Мои статьи</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Настройки</a>
                    <ul class="dropdown-menu">
                        {% if perms.mailingApp.view_massage %}
                        <li><a class="dropdown-item" href="#">Сообщение</a></li>
                        {% endif %}
                        {% if perms.mailingApp.view_mailing %}
                        <li><a class="dropdown-item" href="#">Рассылки</a></li>
                        {% endif %}
                        {% if perms.usersApp.view_user %}
                        <li><a class="dropdown-item" href="#">Пользователи</a></li>
                        {% endif %}
                        <li><a class="dropdown-item" href="#">Клиенты</a></li>
                        <li><a class="dropdown-item" href="#">Создать блог</a></li>

                    </ul>
                </li>
            </ul>
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'usersApp:logout' %}">
                {% csrf_token %}
                <a href="/admin" class="btn btn-outline-warning" type="submit">Администратор</a>
                <a href="{% url 'usersApp:profile' %}" class="btn btn-outline-secondary" type="submit">Профиль</a>
                <button class="btn btn-outline-danger" type="submit">Выйти</button>
            </form>
            {% else %}
            <form method="post" action="{% url 'usersApp:login' %}">
                {% csrf_token %}
                <a href="/admin" class="btn btn-outline-warning" type="submit">Администратор</a>
                <button class="btn btn-outline-success" type="submit">Войти</button>
            </form>
            <form method="post" action="{% url 'usersApp:registration' %}">
                {% csrf_token %}
                <button class="btn btn-outline-primary" type="submit">Регистрация</button>
            </form>
            {% endif %}
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

usersApp/templates/usersApp/login.html
{% extends 'usersApp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">Вход</div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

usersApp/templates/usersApp/main.html
{% extends 'usersApp/base.html' %}

{% block content %}
{% endblock %}

usersApp/templates/usersApp/registration.html
{% extends 'usersApp/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

usersApp/templates/usersApp/user_confirm_delete.html
{% extends 'usersApp/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Вы действительно хотите удалить {{ object.email }}?</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'usersApp:profile' %}" class="btn btn-primary">Отмена</a>
                    </form>

                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

usersApp/templates/usersApp/user_detail.html
{% extends 'usersApp/base.html' %}
{% block content %}
{% load my_tags %}

<div class="image-container">


    <img src="{{ object.photo|mymedia }}" width="200" height="200">
</div>

<div class="col-12">

    <div class="row">

        <div class="col-6">

            <div class="card mb-4 box-shadow">

                <div class="card-header">
                    <tr>
                        <h1>Профиль</h1>
                    </tr>
                </div>

                <div class="card-body">

                    <table class="table table-striped">

                        <tr>
                            <td class="w-25">Имя</td>
                            <td>{{ object.first_name }}</td>
                        </tr>

                        <tr>
                            <td class="w-25">Фамилия</td>
                            <td>{{ object.last_name }}</td>

                        </tr>

                        <tr>
                            <td class="w-25">Почта</td>
                            <td>{{object.email}}</td>
                        </tr>

                        <tr>
                            <td class="w-25">Подтверждение</td>
                            {% if object.is_confirm %}
                            <td>Да</td>
                            {% else %}
                            <td>Нет</td>
                            {% endif %}
                        </tr>

                        <tr>
                            <td class="w-25">Права менеджера</td>
                            {% if object.is_staff%}
                            <td>Да</td>
                            {% else %}
                            <td>Нет</td>
                            {% endif %}
                        </tr>

                        <tr>
                            <td class="w-25">Права администратора</td>
                            {% if object.is_superuser%}
                            <td>Да</td>
                            {% else %}
                            <td>Нет</td>
                            {% endif %}
                        </tr>


                    </table>

                    {% if perms.usersApp.view_user %}
                    <a href="#"
                       class="btn btn-lg btn-block btn-outline-primary">Назад</a>
                    {% endif %}

                    {% if user == object %}
                    <a href="{% url 'usersApp:update' %}" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                    {% endif %}

                    {% if perms.usersApp.delete_user %}
                    <a href="{% url 'usersApp:delete' %}"
                       class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
                    {% endif %}

                </div>

                <div class="card-footer">

                    {% if perms.usersApp.set_active and not user == object %}
                    <form method="post" action="#">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">
                            {% if object.is_active %}
                            Заблокировать
                            {% else %}
                            Разблокировать
                            {% endif %}
                        </button>
                    </form>
                    {% endif %}

                    {% if user.is_confirm is not True and user == object %}
                    <form method="post" action="#">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success">Авторизоваться</button>
                    </form>
                    {% endif %}

                </div>

            </div>

        </div>

        <div class="col-3">

            <div class="card">

                <div class="card-header">Список клиентов</div>

                <div class="card-body">

                    {% for client in clients %}
                    <div class="d-flex text-body-secondary pt-3">

                        <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32"
                             xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32"
                             preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#007bff"/>
                            <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
                        </svg>

                        <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
                            <div class="d-flex justify-content-between">
                                <strong class="text-gray-dark">{{ client.first_name}} {{ client.last_name }}</strong>
                                <a href="{% url 'mailingApp:client_detail' object.pk %}">Перейти</a>
                            </div>

                            <span class="d-block">{{ client.email }}</span>
                        </div>
                    </div>
                    {% endfor %}

                </div>

            </div>

        </div>


        <div class="col-3">

            <div class="card">

                <div class="card-header">Список рассылок</div>

                <div class="card-body">

                    {% for mailing in mailings %}
                    <div class="d-flex text-body-secondary pt-3">

                        <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32"
                             xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32"
                             preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#007bff"/>
                            <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
                        </svg>

                        <div class="pb-3 mb-0 small lh-sm border-bottom w-100">

                            <div class="d-flex justify-content-between">
                                <strong class="text-gray-dark">{{ mailing.name }}</strong>
                                {% if mailing.status == 'create'%}
                                <strong class="text-gray-dark">Создана</strong>
                                {% elif mailing.status == 'launched' %}
                                <strong class="text-gray-dark">Запущена</strong>
                                {% endif %}
                                <a href="#">Перейти</a>

                            </div>

                        </div>

                    </div>

                    {% endfor %}

                </div>

            </div>

        </div>

    </div>

</div>
{% endblock %}

usersApp/templates/usersApp/user_form.html
{% extends 'usersApp/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Редактировать пользователя</div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </form>
                </div>
                {% if user == user_profile %}
                <div class="card-footer">
                    <a href="{% url 'usersApp:change_pass' %}" class="btn btn-danger">Сменить пароль</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}